"""
Applet: Hoa Mission
Summary: Daily bravery mission
Description: Hoa walks in and presents today's bravery challenge, scrolling across the screen.
"""

load("render.star", "render")
load("encoding/base64.star", "base64")

WALK_IN = base64.decode("""
R0lGODlhQAAgAIEAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICQAAACwAAAAAQAAgAAAISwABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLF
ixgzatzIsaPHjyBDihxJsqTJkyhTqlzJsqXLlzBjypxJs6bNmzhz6tzJs6fPnyADAgAh+QQICQAAACwAAAAAQAAgAIFURDcCAQEAAAAAAAAITwAFCBxIsKDB
gwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyhTjgygsqXLlzBjypxJsyZMADYX4szJs6fPn0CDCh06NCAAIfkECAkAAAAsAAAAAEAAIACC
mGdWVEQ3WjcnOjInAwQDAgEBAAAAAAAACFoADQgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48gQ4ocSbKkyZMoGxZIybKly5cwYyokIPPhgJoO
b+JkGCDAzoUAfP5MKGCo0aNIkypdyrSp04AAIfkECAkAAAAsAAAAAEAAIACD4p2N7Yl2639s4YZyyYNv03BcmGdWgEw2VEQ3WjcnOjInCw0JAwQDAgEBAAAA
AAAACG8AHQgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48gQ4ocSbKkyY0LTmI84KCByooGXlpEILMiy5oTY+KUWIDBzogDFPyEGEDoUIcCENA8
yhCAgaVMFRJIEJVhyqpYs2rdyrWr168PAwIAIfkECAkAAAAsAAAAAEAAIACE9+LD1rSi4p2NzJ2J7Yl2639s4YZyyYNv73Rf6m5a03BcmGdWgEw2VEQ3Wjcn
OjInHRoTCw0JAwQDAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACI0AKQgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48g
Q4ocqRACyY0DTmoEsCCCyosAADCgMOElxZgLbFY8EKCBTooICsz8KdFAgJxEIw4IoEBCUogGBBh48PRhggQEqFZteLVAA59bFxIgIGAB2LAJFSg44ADtwgcP
XLqdS7eu3bt48+q1GBAAIfkECAkAAAAsAAAAAEAAIACE9+LD1rSi4p2NzJ2J7Yl2639s4YZyyYNv73Rf6m5a7GtW03BcmGdWgEw2VEQ3WjcnOjInHRoTCw0J
AwQDAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACJwAKwgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48gQz6MILLjAJIlNQIY
kFIlAAYSWl4MAABAgwoUZFI0UJOBzooFDgRw8JNiAAQFbhaVOMBAAJ9LIyIYEGDBhKgQFRgQYAAC1ocJwhLw+rVh2AQFHBAtu7AAAQICGKxlm3CB3QMP6C6M
AAFCTL2AAwseTLiw4cMeAwIAIfkECAkAAAAsAAAAAEAAIACE9+LD1rSi4p2NzJ2J7Yl2639s4YZyyYNv73Rf6m5a7GtW7GlV03BcmGdWgEw2VEQ3WjcnOjIn
KCcYHRoTCw0JAwQDAgEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKkALwgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48QI4D8OGDCyI4G
Sp7caADAgJUaWwJoQAHmRQYBAABwcMGCTYoCZDb4WbFAgQMBHhAFGgBBAZ5LJQYYYCDA0KgRCyAYEIBBBawQFygwEFQkWIcKEqglYPYsw7RqCzxQ6nYhgQIE
CAhoQLduQgaAGRyA4HehhAkRItQszLix48eQI0ue/DMgACH5BAgJAAAALAAAAABAACAAhPfiw9a0ouKdjcydie2Jdut/bOGGcsmDb+90X+puWuxrVuxpVdNw
XJhnVshQPIBMNlREN1o3JzoyJygnGB0aEwsNCQMEAwIBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAi5ADEIHEiwoMGDCBMqXMiwocOHECNKnEixosWLGDNq
3Mixo8ePECGA/MhAwsiOAQZQOLnRgAGVLDMKMABgQEyMMwEAaFDhZkUEDALofIDhgk+JAXLuPDoxQIECBwKIZBoRgYAACAoQpQpRQUoDARpwhbigAIIBARhY
GOtwwQIFBmaaZMvwbYK7BObSVWj3bgEIU/ciLECAMAEBDQILNuiAgWMGByIsTjhhAgUJEnpO3sy5s+fPoENXDAgAIfkECAkAAAAsAAAAAEAAIACE9+LD1rSi
4p2NzJ2J7Yl2639s4YZyyYNv73Rf6m5a7GtW7GlV03Bc2F1ImGdWyFA8oU04gEw2VEQ3WjcnOjInKCcYHRoTCw0JBggFAwQDAgEBAAAAAAAAAAAAAAAAAAAA
CMkANwgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLFjQwoeQwosIEGkRwQMQJrcWCDAAAsrNSYwYOBlTIwDBBgAMODmxZw7ATi44JNiA5QBAACIsEFD
0YgMAuhU6uCpxAMBChTAWtIqxKMCAiAowNTrwwUKXBoIUNWsQwULCiAYEIBBBrcNF+hVYECnSrwK9yYYTOAvYISCB5PsevgggQKPCRAQ4IBx44IQHjDYzODA
hMsIMVSoYIECBaKgU6tezbq169cUAwIAIfkECAkAAAAsAAAAAEAAIACE9+LD1rSi4p2NzJ2J7Yl2639s4YZyyYNv73Rf6m5a7GtW7GlV03Bc2F1ImGdWyFA8
vUUwoU04gEw2VEQ3WjcnOjInKCcYHRoTCw0JBggFAwQDAgEBAAAAAAAAAAAAAAAACNwAOQgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYKV7IyJEhgwodQx5M
UGCCyJMCGyD4iFJkgwIBBmxsybFBAgMGZNLM+GCAAAMABuzE2PMnAAAOMAytCEElgwBHJXDYsFQihKdGkVadCOFAgAIFvJrcGrEpAgEBEBSQShYihAUKYhoI
4KAtxAcKFhRAMCAAAw12HTZYQFiBgZ8gAzMcDDeBYwKJFStkrMAxyQljJSNEQKBAZwIEBDjIrNlghAgPGKhmcIBC6YQYMliwcKFCBaWvc+vezbu379/AJQcE
ACH5BAgJAAAALAAAAABAACAAhPfiw9a0ouKdjcydie2Jdut/bOGGcsmDb+90X+puWuxrVuxpVdNwXNhdSJhnVshQPL1FMKFNOKBDL4BMNlREN1o3JzoyJygn
GB0aEwsNCQYIBQMEAwIBAQAAAAAAAAAAAAjoADsIHEiwoMGDCBMqXMiwocOHECNKnEixosWLGClOwJCx48IEDCx4HGkwQoICFEiq7DChAYKQK0e2LBBgAMeY
GVsmMGDAJk6MEx4MEGAAwICfFyMIJQoAgIMMSClGgOCSQYCmEzpwiBpxqlWmTrlKlADhQIACBcymFAuRrEsBARAUyMr2IQQICxTUNBDAQV27DxQsKIBgQAAG
G/42pLqgsQIDREUqXsg4b4LLBCRPTlhZweWTFNZuPvgAAYECpwkQEOBA9OiCEyIoZUCbwYEKrxFeyKDhwgUMFixAzU28uPHjyJMrXz45IAAh+QQICQAAACwA
AAAAQAAgAIT34sPWtKLinY3MnYntiXbrf2zhhnLJg2/vdF/qblrsa1bsaVXTcFzYXUiYZ1bIUDy9RTChTTigQy+ATDZURDdaNyc6MicoJxgdGhMLDQkGCAUD
BAMCAQEAAAAAAAAAAAAI+wA7CBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgpOpiAIaNHhRMSMLDwsWRBDRESFKBgsmWHCQ0QjHRZEmaBAAM60swIM4EBAzl3
XuQw4cEAAQYADBBqEaVRpAAAOMjAdOKGCBBiMggQdUIHDlUhooSwFarUsBE3SIBwIECBAm1Zon2oNisCAQEQFPA61yEGCBAWKMBpIICDvg4rQHigYEEBBAMC
MNiAmOHaBgsyKzCAlGRlhYAxC05AmoDnzwhDayatkoJc1AYfPEBAoEBtAgQEOHgNm2CFCREiPGBAnMGBCr0PYriQQcOFCxgsWKCavLr169iza9/OvXJAACH5
BAgJAAAALAAAAABAACAAhPfiw9a0ouKdjcydie2Jdut/bOGGcsmDb+90X+puWuxrVuxpVdNwXNhdSJhnVshQPL1FMKFNOKBDL4BMNlREN1o3JzoyJygnGB0a
EwsNCQYIBQMEAwIBAQAAAAAAAAAAAAj/ADsIHEiwoMGDCBMqXMiwocOHECNKnEixosWLGClqqOBgAoaMIBFSmDAhAQMLIVMOtJBBQ4QEBSionNlhQgMEJ2mm
tFkgwICPOjPaTGDAwM+gFzlMeDBAgAEAA5BadMnUKQAADjJInbghAoSbDAJcndCBw1aILiGEtYr1bMQNEiAcCFCgwFyZbh/C/YpAQAAEBcjmdYgBAoQFCnwa
COBgsMMKEB4oWFAAwYAADDY4XqghboMFoBUYcIpyc0ILhj8jTsCaQGnTBjdA/hqaNUwKeGETzCDhwQMEBAoEJ0BAgIPcugVimFBhQoQIDxhIZ3CgQvKCFy5g
uNAyOwYLLK+LCx9Pvrz58+jTOw4IACH5BAgJAAAALAAAAABAACAAhPfiw9a0ouKdjcydie2Jdut/bOGGcsmDb+90X+puWuxrVuxpVdNwXNhdSJhnVshQPL1F
MKFNOKBDL4BMNlREN1o3JzoyJygnGB0aEwsNCQYIBQMEAwIBAQAAAAAAAAAAAAj/ADsIHEiwoMGDCBMqXMiwocOHECNKnEixosWLGCtqqOBgAoaMIBFSmDAh
AQMLIVMOtJBBQ4QEBSionNlhQgMEJ2mmtFkgwICPOjPaTGDAwM+gFzlMeDBAgAEAA5BadMnUKQAADjJInbghAoSbDAJcndCBw1aILiGEtYr1bMQNEiAcCFCg
wFyZbh/C/YpAQAAEBcjmdYgBAoQFCnwaCOBgsMMKEB4oWFAAwYAADDY4XqghboMFoBUYcIpyc0ILhj8jTsCaQGnTBjdA/hqaNUwKeGETzCDhwQMEBAoEJ0BA
gIPcujtowDChwoQIER4wmM7gQIXkBDFcuKC95XYMFlhiDB9Pvrz58+jTqx8cEAAh+QQICQAAACwAAAAAQAAgAIT34sPWtKLinY3MnYntiXbrf2zhhnLJg2/v
dF/qblrsa1bsaVXTcFzYXUiYZ1bIUDy9RTChTTigQy+ATDZURDdaNyc6MicoJxgdGhMLDQkGCAUDBAMCAQEAAAAAAAAAAAAI/wA7CBxIsKDBgwgTKlzIsKHD
hxAjSpxIsaLFixgzatyIUEMFBxMwcBwpkMKECQkYWCDJ0UIGDRESFKDAcuSEBghU1tx4s0CAASJ3YryZwIABoEItcpjwYIAAAwAGJK0Is+lTAAAcZJgqcUME
CDgZBMA6oQMHrg9hQhB7NStaiBskQDgQoEABujTfOowLFoGAAAgKlNXbEAMECAsU/DQQwAHhhhUgPFCwoACCAQEYbHisUIPcBgtCKzDwdCVnhBYOg06coDUB
06cLbogMVnRrmRTyxh6YQcKDBwgIFBBOgIAAB7p3a8AwocKECBEeMJjO4ECF3QQxXLig/eV2DBZcYgsfT768+fPo05MMCAAh+QQICQAAACwAAAAAQAAgAIT3
4sPWtKLinY3MnYntiXbrf2zhhnLJg2/vdF/qblrsa1bsaVXTcFzYXUiYZ1bIUDy9RTChTTigQy+ATDZURDdaNyc6MicoJxgdGhMLDQkGCAUDBAMCAQEAAAAA
AAAAAAAI/wA7CBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatyYUEMFBxMwcBwpkMKECQkYWCDJ0UIGDRESFKDAcuSEBghU1tx4s0CAASJ3YryZwIABoEIt
cpjwYIAAAwAGJK0Is+lTAAAcZJgqcUMECDgZBMA6oQMHrg9hQhB7NStaiBskQDgQoEABujTfOowLFoGAAAgKlNXbEAMECAsU/DQQwAHhhhUgPFCwoACCAQEY
bHisUIPcBgtCKzDwdCVnhBYOg06coDUB06cLbogMVnRrmRTyxh6YQcKDBwgIFBBOgIAAB7p3a8AwocKECBEeMJjO4ECF3QQxXLig/eV2DBZcYgsfT768+fPo
048MCAA7
""")

STILL = base64.decode("""
R0lGODlhQAAgAIQAAPfiw9a0ouKdjcydie2Jdut/bOGGcsmDb+90X+puWuxrVuxpVdNwXNhdSJhnVshQPL1FMKFNOKBDL4BMNlREN1o3JzoyJygnGB0aEwsN
CQYIBQMEAwIBAQAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQACQAAACwAAAAAQAAgAEAI/wA7CBxIsKDBgwgTKlzYwUIGDRESFKDAsKLFiwU3SIBw
IECBAh0pYhw5UgOGCRUmRIjwgIFLBgcqkJxJs6bNkRwmPBggwACAATeDItSwscGCowoM9LQgtKnTp1CjWtRQwcEEDFKlTmhQIMAArFmDbogAoQECBgEAAJjQ
gUPYmRggQFigwKuBAA7ektxQQa5RugkCTxSpt7Dhw4gTK17MeCSFCRMSMGDaGOPWs5QrM9yawICBr5oVQtzZU62DDKEPQoSAtjSAvKkzFkUgIACCAmxjE+z7
QMGCAggGBGCwQbdAC36RBk5AIHPqDBIePEBAoEB1AgQEOCCsGcOFC94ffgvHYMGh8fPo00sNCAA7
""")

def main(config):
    challenge = config.get("challenge", "Try something brave today")
    done = config.get("done", "false") == "true"
    label = "DONE!" if done else "MISSION"
    label_color = "#FFD23C" if done else "#9599C7"
    text_color = "#FFD23C" if done else "#FFFFFF"

    content = render.Stack(
        children = [
            render.Image(src = STILL),
            render.Padding(
                pad = (18, 3, 0, 0),
                child = render.Column(
                    children = [
                        render.Text(content = label, font = "CG-pixel-3x5-mono", color = label_color),
                        render.Padding(
                            pad = (0, 3, 0, 0),
                            child = render.Marquee(
                                width = 44,
                                height = 12,
                                scroll_direction = "horizontal",
                                offset_start = 20,
                                offset_end = 20,
                                delay = 60,
                                child = render.Text(content = challenge, color = text_color),
                            ),
                        ),
                    ],
                ),
            ),
        ],
    )

    return render.Root(
        delay = 70,
        child = render.Sequence(
            children = [
                render.Image(src = WALK_IN),
                content,
            ],
        ),
    )
